### ISSUE TITLE
Building for armv7-a Android issues

### ISSUE THREAD

**Issue by licaon-kter** [jedisct1/dnscrypt-proxy#651]
@jedisct1 Can you share you setup for building Android packages? I'm having some issues here, on NDK 14b.

With **libsodium** build as default with `NDK_PLATFORM="android-24"` and `NDK_PLATFORM_COMPAT="android-16"`, building **dnscrypt-proxy** with default `19` and `16` it will error out on the libsodium test in configure with: 
```
<path>/lib/libsodium.so: error: undefined reference to '__aeabi_memclr', version 'LIBC_N'
<path>/lib/libsodium.so: error: undefined reference to '__aeabi_memset8', version 'LIBC_N'
<path>/lib/libsodium.so: error: undefined reference to '__aeabi_memset', version 'LIBC_N'
<path>/lib/libsodium.so: error: undefined reference to '__aeabi_memcpy', version 'LIBC_N'
<path>/lib/libsodium.so: error: undefined reference to '__poll_chk', version 'LIBC'
<path>/lib/libsodium.so: error: undefined reference to '__aeabi_memclr4', version 'LIBC_N'
<path>/lib/libsodium.so: error: undefined reference to '__aeabi_memclr8', version 'LIBC_N'
<path>/lib/libsodium.so: error: undefined reference to '__aeabi_memcpy8', version 'LIBC_N'
<path>/lib/libsodium.so: error: undefined reference to '__memchr_chk', version 'LIBC'
<path>/lib/libsodium.so: error: undefined reference to '__aeabi_memmove', version 'LIBC_N'
```
(this happens every time NDK_PLATFORM=/=NDK_PLATFORM_COMPAT, afaics)

With **libsodium** build with `NDK_PLATFORM="android-19"` and `NDK_PLATFORM_COMPAT="android-16"`, building **dnscrypt-proxy** with default `19` and `16` it will still error out on the libsodium test in configure with: :
```
<path>/lib/libsodium.so: error: undefined reference to '__strchr_chk', version 'LIBC'
<path>/lib/libsodium.so: error: undefined reference to '__strlen_chk', version 'LIBC'
<path>/lib/libsodium.so: error: undefined reference to '__strrchr_chk', version 'LIBC'
```

With **libsodium** build with `NDK_PLATFORM="android-19"` and `NDK_PLATFORM_COMPAT="android-19"`, building **dnscrypt-proxy** with `19` and `19` it will error out on linking **libevent** with:
```
../.libs/libevent_core.a(log.o):log.c:function _warn_helper: error: undefined reference to 'stderr'
../.libs/libevent_core.a(evutil.o):evutil.c:function _evutil_weakrand: error: undefined reference to 'random'
../.libs/libevent_core.a(select.o):select.c:function select_dispatch: error: undefined reference to 'random'
../.libs/libevent_core.a(poll.o):poll.c:function poll_dispatch: error: undefined reference to 'random'
../.libs/libevent_core.a(signal.o):signal.c:function _evsig_set_handler: error: undefined reference to 'sigfillset'
```

Making them all `21` errors out only with:
```
../.libs/libevent_core.a(log.o):log.c:function _warn_helper: error: undefined reference to 'stderr'
```

Making them all `23` works ok, albeit I guess this will not actually work on devices with Android <6.0, right?

I would like to build this for SDK19 too (for this: https://github.com/smarek/android-unbound-dns/issues/18#issuecomment-298909959)

Not sure if this is #505 actually.

**Comment by jedisct1** [comment]
I'm not able to build it either.

**Comment by licaon-kter** [comment]
ROFLOL!

I'll limit my project to prebuild binaries for the moment then.

**Comment by jedisct1** [comment]
I'm gonna stop supporting Android. It's too much of a hassle.

**Comment by KrasnayaPloshchad** [comment]
CC @meefik

**Comment by licaon-kter** [comment]
The new commits help (clang and all that), making NDK_PLATFORM=NDK_PLATFORM_COMPAT=19/21/23 works ok, mixing them still fails.

What I don't know yet, if there are any drawbacks for running build 19 on >21?

**Comment by jedisct1** [comment]
Jelly Bean (API level 16) is still installed on a significant number of devices, so we still have to support that :(

But it doesn't seem to be compatible with recent toolchains, and API level 16 is not compatible with 64-bit platforms either.

I'm still looking for a way to use the current SDK and still produce libraries and apps that would work on Jelly Bean. If that is possible, at all.

I don't know much about Android except that it looks like an insane mess.

libsodium is built with NDK platform 24, but targeting API level 16, and apparently, JNI bindings seem to work using this configuration. So maybe all it takes is some magical compilation flag to be able to compile native apps using the same configuration.
I don't know. I'm completely lost when it comes to Android, and could really get some help here.

**Comment by rdcw** [comment]
@jedisct1 Isn't the JNI bindings overriding the default platform targets to 21 and 9?

https://github.com/joshjdevl/libsodium-jni/blob/master/build.gradle#L74

**Comment by jedisct1** [comment]
@rdcw Interesting, I didn't know that. And they don't even bother with `NDK_PLATFORM_COMPAT`.

If the default compile script don't work, it's sad that they overrode the defaults instead of reporting it, but well, if targeting platform 9 doesn't have any downsides, let's do that :)

**Comment by jedisct1** [comment]
OTOH, API level 9 is really really really old, and devices running this are pretty much nonexistent. 

Which means that we can't seriously pretend to support this, as it would be barely tested, if at all.

Would using platform 16 for 32-bit platforms, and 21 for 64-bit platforms work?

**Comment by haraldj** [comment]
Dear Frank, any chance an android package of version 1.9.5 will be released by you :-/ ?

**Comment by haraldj** [comment]
JFYI: Compiling both libsodium (normal mode) and dnscrypt-proxy (XChaCha20 enabled) with API level 19 works, program seems to run without problems. The only issue I currently have is the dnscrypt script which can't correctly enable oder disable dnscrypt-proxy.

**Comment by licaon-kter** [comment]
@haraldj What use case exactly? Root, no-root?

**Comment by haraldj** [comment]
> @haraldj What use case exactly? Root, no-root? 

Internal DNS with dnscrypt-proxy as client and unbound on server, currently running as root. Don't know enough about user management in android to run it as user (but when binding the daemon to port 5353 the only thing which would need to run as root would be the iptables rules I guess).

**Comment by licaon-kter** [comment]
What's the problem exactly?

**Comment by haraldj** [comment]
> What's the problem exactly?

With the script you mean? First calling the script with enable doubles the nat rules as it adds the rules in the script itself AND the init script does it afterwards too and the disable does not work because there is no pidfile (did not check if there is none or only somewhere else located).

**Comment by itspull** [comment]
@haraldj  as for the script, here's what I do. Comment out the iptables rules in the init and have the enable/disable script reflect the address and port number you want dnscrypt listening on.

I brought the very same thing up about the double rules in an issue a week or two ago.

I don't think you need a pid file to stop dnscrypt, a simple kill command should stop all running instances of it.

**Comment by haraldj** [comment]
> @haraldj  as for the script, here's what I do. Comment out the iptables rules in the init and have the enable/disable script reflect the address and port number you want dnscrypt listening on.

But when you restart the smartphone and just use the init script then the iptables rules won't be set.

> 
> I brought the very same thing up about the double rules in an issue a week or two ago.

Ok

> 
> I don't think you need a pid file to stop dnscrypt, a simple kill command should stop all running instances of it.

Well I guess this should then be changed in the script?

**Comment by CHEF-KOCH** [comment]
I might can help on this, but currently I want to make the switch from Android Studio to VS 2017 (because I'm daily using VS and it supports now Android/NDK).

> But when you restart the smartphone and just use the init script then the iptables rules won't be set.

Please share your rules and provide your binary, I'm curious because some iptables binaries have a known 'startup' issue, which got fixed in e.g. AFWall+ (you can replace it with them).

**Comment by haraldj** [comment]
> I might can help on this, but currently I want to make the switch from Android Studio to VS 2017 (because I'm daily using VS and it supports now Android/NDK).
> 
>> But when you restart the smartphone and just use the init script then the iptables rules won't be set.
> 
> Please share your rules and provide your binary, I'm curious because some iptables binaries have a known 'startup' issue, which got fixed in e.g. AFWall+ (you can replace it with them). 

Thanks for the information will have a look at this ASAP

**Comment by CHEF-KOCH** [comment]
**Easy self-compile guide**:

1. Extract the NDK (unzip android-ndk-rXXb.zip )
2. Run `export ANDROID_NDK_HOME=<NDK Location>`
3. Extract libsodium and dnscrypt-proxy from their official sources.
4. Enter the folder of libsodium/dist-build, then edit android-build.sh such that NDK_PLATFORM:-android-16 becomes NDK_PLATFORM:-android-24. Then modify android-armv8-a.sh and add `-mtune=cortex-a57.cortex-a53 -mcpu=cortex-a57.cortex-a53` to the end of CFLAGS.
5. Return to libsodium root folder (cd ..) and do ./autogen.sh then ./dist-build/android-armv8-a.sh. When the script finishes it will tell you where the output is.
6. (Optional) Run android-toolchain-armv8-a/aarch64-linux-android/bin/strip on the output .so (typically in libsodium-android-armv8-a/lib/libsodium.so)
7. Now we do `export SODIUM_ANDROID_PREFIX=<libsodium output>`
8. Enter the folder of dnscrypt, do the same modifications to dnscrypt's dist-builds. Again, do ./autogen.sh and ./dist-build/android-armv8-a.sh.
9. Now you have a fresh compilation of AArch64 dnscrypt-proxy! It's usually dnscrypt-proxy-android-armv8-a.zip
10. Finally, we need to edit the zip file and rename the /system/lib folder to lib64, and change references in updater-script and /system/addon.d/75-dnscrypt.sh.
11. (Optional) Add --ephemeral-keys to 99dnscrypt for extra security.

**Compiler flags I used**:

`NDK_PLATFORM:-android-16 to NDK_PLATFORM:-android-24
add -fPIE to CFLAGS
export LDFLAGS="-fPIE -pie"`

I'll post Visual Studio (Community Edition) compiling guide as soon I got more time. SO that everyone can easy peasy compile it. 👍

**Comment by licaon-kter** [comment]
@CHEF-KOCH Did you get a chance to test the binaries in Termux too? (no-root I mean)

**Comment by CHEF-KOCH** [comment]
Nope, sorry - I only tried with root privileges. But I will check it and update the post.

**Comment by haraldj** [comment]
> **Easy self-compile guide**:
> 
> 1. Extract the NDK (unzip android-ndk-rXXb.zip )
> 2. Run `export ANDROID_NDK_HOME=<NDK Location>`
> 3. Extract libsodium and dnscrypt-proxy from their official sources.
> 4. Enter the folder of libsodium/dist-build, then edit android-build.sh such that NDK_PLATFORM:-android-16 becomes NDK_PLATFORM:-android-24. Then modify android-armv8-a.sh and add `-mtune=cortex-a57.cortex-a53 -mcpu=cortex-a57.cortex-a53` to the end of CFLAGS.
> 5. Return to libsodium root folder (cd ..) and do ./autogen.sh then ./dist-build/android-armv8-a.sh. When the script finishes it will tell you where the output is.
> 6. (Optional) Run android-toolchain-armv8-a/aarch64-linux-android/bin/strip on the output .so (typically in libsodium-android-armv8-a/lib/libsodium.so)
> 7. Now we do `export SODIUM_ANDROID_PREFIX=<libsodium output>`
> 8. Enter the folder of dnscrypt, do the same modifications to dnscrypt's dist-builds. Again, do ./autogen.sh and ./dist-build/android-armv8-a.sh.
> 9. Now you have a fresh compilation of AArch64 dnscrypt-proxy! It's usually dnscrypt-proxy-android-armv8-a.zip
> 10. Finally, we need to edit the zip file and rename the /system/lib folder to lib64, and change references in updater-script and /system/addon.d/75-dnscrypt.sh.
> 11. (Optional) Add --ephemeral-keys to 99dnscrypt for extra security.
> 
> **Compiler flags I used**:
> 
> `NDK_PLATFORM:-android-16 to NDK_PLATFORM:-android-24
> add -fPIE to CFLAGS
> export LDFLAGS="-fPIE -pie"`
> 
> I'll post Visual Studio (Community Edition) compiling guide as soon I got more time. SO that everyone can easy peasy compile it. 👍 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/jedisct1/dnscrypt-proxy/issues/651#issuecomment-326418900

Thanks for the info but I compile for 32 bit :-).

**Comment by haraldj** [comment]
> @CHEF-KOCH Did you get a chance to test the binaries in Termux too? (no-root I mean)

How would this be possible to achieve? Like in "normal" linux?

**Comment by haraldj** [comment]
> Nope, sorry - I only tried with root privileges. But I will check it and update the post. 

This would be a very cool and interesting thing to achieve I guess :-)

**Comment by licaon-kter** [comment]
@haraldj 

ARMv7 32-bit is already covered by the included scripts, he wanted ARMv8 64-bit.

Yes, install Termux and use that command line line normal Linux.

**Comment by haraldj** [comment]
> @haraldj 
> 
> ARMv7 32-bit is already covered by the included scripts, he wanted ARMv8 64-bit.
> 
> Yes, install Termux and use that command line line normal Linux.

Thanks but it's not available for the used android version :-)

**Comment by licaon-kter** [comment]
Do detail vhat you mean exactly? What device? What Android version?

**Comment by haraldj** [comment]
> Do detail vhat you mean exactly? What device? What Android version?

The android version is too low to be supported by Termux (maybe the Termux app itself could be supported but not the Linux environment, already googled it).
